// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FileInfo struct {
	Name    string `json:"name"`    // 文件名
	Path    string `json:"path"`    // 完整路径
	Size    int64  `json:"size"`    // 文件大小(字节)
	IsDir   bool   `json:"isDir"`   // 是否是目录
	ModTime string `json:"modTime"` // 修改时间
}

type GetFilesRequest struct {
	Path string `form:"path"` // 文件夹路径
}

type GetFilesResponse struct {
	Code    int        `json:"code"`
	Message string     `json:"message"`
	Data    []FileInfo `json:"data"`
}
